name: DAST
on:
  push:
    branches:
      - main

jobs:
  dast:
    name: DAST
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install Docker Compose (if needed)
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create isolated network
        run: docker network create --driver bridge isolated

      - name: Build AUT
        run: docker build -t my-php-site:latest .

      - name: Run AUT using Docker Compose
        run: docker compose up -d

      - name: Get AUT URL
        run: |
          URL=http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1)
          echo "URL=$URL" >> $GITHUB_ENV

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: ${{ env.URL }}
          allow_issue_writing: false
          cmd_options: '-a'

      - name: Upload ZAP Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-results
          path: zap_report.html

      - name: Stop Docker
        run: docker stop docker-apache || true
